### ISSUE TITLE
API 기능 고도화

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#52]
# Description

현재 첫번째 개발 사이클 완료를 목표로 최소한의 기능만 구현했습니다.

**실제 프론트엔드에서 사용 가능한 API**를 만들어주세요.
- USER 
- Event
- Reservation
- Bookmark

**기능을 새롭게 추가하는게 아니라**, 실제로 사용 가능한 정보를 담고, 그에 맞는 API 만 만들어주시면 됩니다.
- 예를들어 **좌석 예약 기능을 추가하는게 아니라**, 공연 리스트, 예매 리스트 조회에 페이지네이션을 추가하는 경우

해당 이슈에 **의존성**을 가집니다
- #4 
- #50 
- #39 
- #36 
    - [Wiki - HTTP Response](https://github.com/f-lab-clone/ticketing-backend/wiki/Convention#http-response) 형식 준수
    - `@ExceptionHandler` - Custom Error 
- #78 
- #40 
- #37 
- #82 

# To do
- [x]  데이터베이스 설계 ([ERD](https://www.erdcloud.com/team/zs2oRM5AwLfoakQE7) 작성)
- [ ]  API 명세 설계 
- [ ] 기능 구현 (**위 의존성에 정의된 사항을 모두 준수**)

# Test Checklist
- Test Coverage over 80%

**Comment by ParkJeongseop** [comment]
[ERD](https://www.erdcloud.com/d/DpmtTbCnKzknuLzFo)

**Comment by junha-ahn** [comment]
@ParkJeongseop ERD 스크린샷 첨부 부탁드립니다

**Comment by ParkJeongseop** [comment]
# ERD
![티켓팅 시스템](https://github.com/f-lab-clone/ticketing-backend/assets/4309773/73ca6698-3dc8-4c37-94cf-265547bf9f57)
[ERD](https://www.erdcloud.com/d/YbadkYrimpCu5Kois)

현재 구성에 맞게 ERD를 작성하였습니다.

**Comment by junha-ahn** [comment]
1. `booked_at` 은 필요없어보입니다. `created_at` 으로 대체 가능
    - 모든 테이블에 명시없이 created_at, updated_at은 기본으로 생성/사용합니다.
2. role은 현재 필요 없습니다.
3. pw => password
4. username 생성 
5. email varchar(320) 인 이유가 있습니까? (이메일은 320자까지 가능한가요? 아니라면 255로 통일해도 좋을것 같네요)

해당 ISSUE의 ERD는 프론트엔드에서 실제로 사용할 데이터를 포함해야 합니다.
- https://github.com/wlwlsus/allback-with-k8s 해당 깃 레포에 GIF 참고
- https://github.com/f-lab-clone/ticketing-frontend/issues/5#issuecomment-1646860966 참고

**Comment by junha-ahn** [comment]
해당 페이지 청사진을 보고 설계 부탁드립니다! 

![제목 없음-2023-08-14-1752](https://github.com/f-lab-clone/ticketing-backend/assets/41976906/a1c66b32-c212-494a-8840-1cc7217adcf0)

참고
- festa (IT 행사 티켓팅 사이트)
- https://blog.naver.com/trric/222729249130

**Comment by ParkJeongseop** [comment]
이메일 주소 최대길이가 320자입니다.
[what-is-email](https://www.cloudflare.com/ko-kr/learning/email-security/what-is-email/)

> 로컬 부분은 이메일 메시지의 최종 위치를 서버에 알려줍니다. 문자, 숫자, 특정 문장 부호(밑줄 등)가 포함될 수 있습니다. 이메일 주소의 권장 길이는 254자로 제한되지만 (로컬 부분 및 도메인을 포함한) 최대 문자수는 320자입니다.

**Comment by ParkJeongseop** [comment]
![티켓팅 시스템 (1)](https://github.com/f-lab-clone/ticketing-backend/assets/4309773/108e3489-220f-46fd-bde6-c2ff098961f9)

ERD 업데이트 하였습니다.

**Comment by junha-ahn** [comment]
INT Null OR MAX value 에 대해
- https://stackoverflow.com/questions/21286215/how-can-i-include-null-values-in-a-min-or-max
- https://stackoverflow.com/questions/28834499/is-it-better-to-use-null-or-1-to-indicate-infinite-in-integer-columns-of
- https://saturncloud.io/blog/how-do-null-values-affect-performance-in-a-database-search/
- https://www.sqlservercentral.com/blogs/null-values-impact-the-performance-of-max-and-min

**Comment by junha-ahn** [comment]
# 개발 시나리오

## API Upgrade

Bookmark API Upgrade
- [ ] 1. JWT Validation 적용 (#4)
- [ ] 2. Time Convention 적용 (#39, #50)
- [ ] 3. Request Data Validation 적용 (#40)
- [ ] 4. Custom Error 구현 (#36)
- [ ] 5. API 설계 (#37)
       - 실제 사용 가능화 (ex: pagenation, search 등)
- [ ] 6. 쿼리 및 DB 인덱스 설계 
      -  Real MySQL 및 [업무에 바로 쓰는 SQL 튜닝](https://devkly.com/book/sql-turing/) 참고

**Comment by junha-ahn** [comment]
@minjun3021  ERD에 따른 수정 부탁드립니다. 

<img width="1158" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/6b043bb6-12c5-4264-ba21-727b453870b4">

> https://www.erdcloud.com/d/YbadkYrimpCu5Kois


변경사항
- `event.title` => `event.name` (= name으로 통일)
- `max_attendees` => `max_reservation_count` (count로 용어 통일)
- `date` => `start_time`/`end_time` (이벤트 시작 ~ 종료)

<img width="966" alt="image" src="https://github.com/f-lab-clone/ticketing-backend/assets/41976906/15aad618-4476-4873-8cf9-1988fd6f88bf">

> 참고: https://festa.io/events

**Comment by junha-ahn** [comment]
# API 고도화 마무리 작업
- 출처: https://sanghaklee.tistory.com/57

## 현재 위반사항
- 2.1. 마지막에 / 포함하지 않는다. : `GET events/`

## 추가사항

- [ ] 3. Set HTTP Headers
  - [ ] 3.1. Content-Location (우선순위 낮음)
  - [ ] 3.2. Content-Type
  - [ ] 3.4. Link
- [ ] 4. Use HTTP methods
  - [ ] 4.2. OPTIONS, HEAD, PATCH를 사용하여 완성도 높은 API를 만든다. 
- [ ] 5.2. HTTP status만으로 상태 에러를 나타낸다 (`moreinfo` 부분을 openDocs에 error_code 설명란으로 할 수 있게 추가)
- [ ] 6.1. 성공 응답은 2XX로 응답한다. (200,201,204 구분, 405 등도..)
- [ ] 7. Use HATEOAS
- [ ] 8. Paging, Ordering, Filtering, Field-Selecting
- [ ] 8.1. Paging
- [ ] 8.2. Ordering
- [ ] 8.3. Filtering
- [ ] 8.4. Field-Selecting
- [ ] 9. Versioning

**Comment by junha-ahn** [comment]
[[ Rest API ] HATEOAS 를 써야 할까 ?](https://soobindeveloper8.tistory.com/646) 
> 하지만 RESTful 을 충족하는 것이 신성한 것으로 간주돼서는 안되며 
> 레벨 2의 서비스가 되는 것이 해당 API 가 레벨 3 의 API 보다 열등하다는 것을 의미하지 않는다.
> HATEOAS 를 구현할지 말지는 API 의 본질과 노력의 가치 여부에 달려있다

해당 내용이 매우 좋네요.

> 해당 표준만으로는 전체 데이터 건수를 알수 없어서 결국엔 표준방법을 사용하기 이전과 같이 Response Body에 페이지네이션 정보가 추가로 들어가야하는데 해당 표준들이 과연 효율적인지에 의문입니다. 또한 저희는 OPEN API를 제공하는 것이아닌 자체 서비스를 위한 API를 개발하는데 API문서 URI를 제공해야하는지도 궁금합니다

**'비효율'에 대한 내용 모두 맞습니다**. 하지만 해당 프로젝트는 사이드 프로젝트이며, `HATEOAS`를 구현 하는 것 자체에 의미를 두고 싶습니다.  다시말해 **표준**을 지키는것에 **큰 의미**를 부여하지는 않고, (구현해본적 없는) 해당 기능을 **구현해보는 경험**에 의미를 두고 싶습니다. 그 과정에서 겪는 문제점이나, 장점과 단점 또는 불편함, 비효율성을 체험하기만 해도 충분한 의미가 있다고 생각합니다.

**Comment by ParkJeongseop** [comment]
좋습니다.

9번항목의 버저닝은
> 웹 서버의 reverse-proxy 기능을 활용한다
> 웹 APP 서버의 라우팅은 버저닝을 제외하고 개발한다. /users, /posts

라고 되어있어 인프라팀에서 nginx 웹서버에서 처리해야될것같습니다.

확인부탁드립니다.
