### ISSUE TITLE
CD: 배포를 위한 환경 세팅 [학습]

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-backend#7]
# Description

배포를 위한 최소 환경 세팅 (학습)

# To do

## 학습 시나리오 1
1. terraform을 이용해 AWS에 EC2 띄우기
2. k8s 직접 세팅하기 (1 master node / 1 worker node~~ / spring boot hello world)
3. git deployment 등으로 repo code(or image) 자동으로 올리기

Test Checklist 
- 2번 작업 후 `curl x.x.x.x:port` (public IP) 를 통해 "Hello World"가 출력되어야 합니다.
- 3번 작업 후 해당 레퍼지토리의 push 이벤트마다 새롭게 이미지가 배포되어야 합니다.

## 학습 시나리오2

1. Terraform EKS로 Hello World 띄우기
2. CD pipeline 구축
3. Helm으로 Prod/QA 환경 구축

# Finally

![image](https://github.com/junha-ahn/kotlin-boot-deployment/assets/41976906/d2c3b54c-bf7a-4baa-8eee-d1a8de303cb7)
- image [from](https://github.com/wlwlsus/allback-with-k8s/tree/main)
- but, we dont use jenkins, we just use git actions for build and push image

Tech Stack
- terraform (AWS)
- git actions (to push image)
- kubernetes
- helm
- EKS
- argoCD

**Comment by junha-ahn** [comment]
[junha-ahn/CLI](https://github.com/junha-ahn/CLI)를 제 개인 ubuntu machine으로 써서 테스트 해보겠습니다. codespace를 이용하면 무료 ubuntu machine이 빠르게 on/off가 가능하네요

**Comment by junha-ahn** [comment]
# terraform을 이용해 AWS에 EC2 띄우기

=> 완료 [terraform config](https://github.com/junha-ahn/kotlin-boot-deployment/blob/main/terraform/ec2.tf)


### 1. 구성도를 직접 손으로 그려보기 
 완료

### 2. kubernetes를 어떻게 설치할지?

https://www.skyer9.pe.kr/wordpress/?p=6630
- 마스터와 워커 노드 각각 설치를 해야한다.

스크립트를 만들어서 자동화를 한다면?
-  terrafrom 에서 해당 스크립트를 먼저 실행하게 하면 모든 worker EC2가 쉽게쉽게 마스터와의 연결을 끝낸다.

다만 해당 설치는 오래걸리니까, worker AMI 이미지를 만들어놓고 복제 떠서 EC2 worker를 생성한다.
- 그리고 연결 과정은 스크립트를 사용한다

### 3. 언제 EKS로 넘어갈까?

- terraform autoscaling group은 ELB 등을 트리거로 scale up 한다
- 만약 내가 가진 kube pod의 특정 트리거로 scale up을 하고 싶다면? 
- 이때 EKS를 사용하는게 맞을까?

**Comment by pRivAte12** [comment]
EKS의 단점 : 좀 비싸다

**Comment by junha-ahn** [comment]
## k8s 설치 중 이슈

NO_PUBKEY 
- https://github.com/kubernetes/website/issues/32207

**Comment by junha-ahn** [comment]
k8s 세팅 중 오류 

# Connection Refused

master (CP) ec2 안에서..,
```
> kubectl get nodes
NAME            STATUS     ROLES           AGE    VERSION
ip-10-0-1-191   NotReady   control-plane   2m4s   v1.27.3

> kubectl get nodes
The connection to the server 10.0.1.191:6443 was refused - did you specify the right host or port?
```

kubectl 로 계속 접근이 불가능해짐... 이유가 뭘까?...

**Comment by junha-ahn** [comment]
Todo
1. worker image AMI 복사 구성
2. 어떻게 하면 worker node가 자동으로 master에 연결되도록 할 수 있을까?

**Comment by junha-ahn** [comment]
리딩 
- https://sunrise-min.tistory.com/entry/Kubernetes-NodePort-vs-LoadBalancer-vs-Ingress

**Comment by junha-ahn** [comment]
### 인쇄 용 자료

도커 태깅 정책
- https://sweethoneybee.tistory.com/30


쿠버네티스는 언제나 자동으로 새로운 이미지를 받아온다??
- https://kubernetes.io/docs/concepts/containers/images/#updating-images
- https://m.blog.naver.com/vefe/221888345952
- https://dongle94.github.io/kubernetes/kubernetes-image-pull-policy/
- https://lance.tistory.com/7 - test 필요

Kubernetest CD
- https://junghyeonsu.tistory.com/65
- https://www.skyer9.pe.kr/wordpress/?p=6834
- https://medium.com/finda-tech/finda-msa%EB%A5%BC-%EC%9C%84%ED%95%9C-kubernetes-%EC%84%B8%ED%8C%85%EA%B3%BC-ci-cd-pipeline-%EA%B5%AC%EC%84%B1-%EA%B7%B8%EB%A6%AC%EA%B3%A0-monitoring-%EC%8B%9C%EC%8A%A4%ED%85%9C-%EA%B5%AC%EC%B6%95-2-ef29380ec474

**Comment by junha-ahn** [comment]
도서 선정
- 24단계 실습으로 정복하는 쿠버네티스 (ebook 존재)
-

**Comment by junha-ahn** [comment]
저녁 Todo
- argo cd 영상을 통해 실습 
- kotlin-boot 프로젝트에도 적용

자료
- EKS best CD pipeline 자료 학습 (향후 구현)
- 해당 하는 Docs 인쇄 후 주말 학습

**Comment by junha-ahn** [comment]
현재 생각하는 최종 구현

![image](https://github.com/junha-ahn/kotlin-boot-deployment/assets/41976906/d2c3b54c-bf7a-4baa-8eee-d1a8de303cb7)
- image [from](https://github.com/wlwlsus/allback-with-k8s/tree/main)
- but, we dont use jenkins, we just use git actions for build and push image


학습 키워드
- kubernetes
- helm
- EKS
- argoCD

**Comment by junha-ahn** [comment]
현재 생각하는 최종 구현

![image](https://github.com/junha-ahn/kotlin-boot-deployment/assets/41976906/d2c3b54c-bf7a-4baa-8eee-d1a8de303cb7)
- image [from](https://github.com/wlwlsus/allback-with-k8s/tree/main)
- but, we dont use jenkins, we just use git actions for build and push image


학습 키워드
- terraform (AWS)
- git actions (to push image)
- kubernetes
- helm
- EKS
- argoCD

**Comment by junha-ahn** [comment]
# 학습 시나리오 2

**Comment by hihahayoung** [comment]
# 학습 시나리오 1

## EndPoint: None 

### pod + service 조합

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kotlin-app
  labels:
    name: kotlin-app
spec:
  containers:
  - name: core
    image: devjunha/kotlin-app:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
        protocol: TCP
    resources:
      requests:
        cpu: 500m
        memory: 1000Mi
```


```yaml
apiVersion: v1
kind: Service
metadata:
  name: kotlin-app-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30001
  selector:
    app: kotlin-app
```

```shell
$ kubectl describe service kotlin-app-service
Name:                     kotlin-app-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=kotlin-app
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.133.216
IPs:                      10.99.133.216
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30001/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

### deployment + service 조합

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-app-deployment
spec:
  selector:
    matchLabels:
      app: kotlin-app
  replicas: 1
  template:
    metadata:
      labels:
        app: kotlin-app
    spec:
      containers:
        - name: core
          image: devjunha/kotlin-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
```

```shell
$ kubectl describe service kotlin-app-service
Name:                     kotlin-app-service
Namespace:                default
Labels:                   <none>
Annotations:              <none>
Selector:                 app=kotlin-app
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.96.139.200
IPs:                      10.96.139.200
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30001/TCP
Endpoints:                192.168.52.67:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

**Comment by pRivAte12** [comment]
# 메모
- Terraform으로 EKS deploy이후 Kubernetes 클러스터에 pod을 띄우는 방법
1. kubectl로 클러스터에 연결하여 사전에 정의한 yaml 파일을 직접 apply 시키기
2. 띄울 pod을 helm 차트로 만들어 놓고 terraform 파일로 EKS 정의시 helm 차트를 자동으로 배포하도록 정의하기

=> 2번으로 접근하기. 

# TODO

- [x] Terraform으로 EKS 띄우기
- [ ] nginx + kotlin application 앱을 yaml 파일로 정의해서 띄우기
- [ ] helm 차트로 만들기
- [ ] Terraform으로 EKS + helm 차트 연결해서 EKS 띄우면 자동으로 helm 차트 받아와서 pod 띄우도록하기

# 기타 궁금한점
- ECR, Docker hub와 같은 Docker container repository에 새로운 버전의 이미지가 푸시되면 어떻게 바로 EKS에 반영할 수 있을까

# 연관 자료
https://developer.hashicorp.com/terraform/tutorials/kubernetes/helm-provider
https://helm.sh/docs/chart_template_guide/
https://opensource.com/article/20/5/helm-charts

**Comment by junha-ahn** [comment]
인쇄 용
- https://blog.leaphop.co.kr/blogs/51
- https://antonputra.com/terraform/how-to-create-eks-cluster-using-terraform/

**Comment by junha-ahn** [comment]
학습 레퍼런스 추천
- terraform-aws 공식 모듈의 [eks_managed_node_group](https://github.com/terraform-aws-modules/terraform-aws-eks/tree/master/examples/eks_managed_node_group] 예제
- terraform-aws 공식 모듈을 사용했고, ArgoCD 까지 setup한 [예제](https://github.com/ravindrasinghh/argocd-setup) (리드미에 유튜브 영상 존재)
